/* Generated by scripts/gen-types.mjs from the vendored contract schema. Do not edit by hand;
 * re-run `npm run gen-types` after `npm run sync-contracts`. */

export interface Values {
  /**
   * @maxItems 16
   */
  attack_rating?: (number | null)[] | null;
  /**
   * @maxItems 16
   */
  characters?:
    | ({
        armor: string | null;
        armor_mdef: number | null;
        armor_pdef: number | null;
        base_hp: number | null;
        base_matk: number | null;
        base_mdef: number | null;
        base_patk: number | null;
        base_pdef: number | null;
        base_sp: number | null;
        boost_level: number | null;
        class_id: string | null;
        group_trinket: string | null;
        hp: number | null;
        id: string | null;
        sp: number | null;
        trinket_1: string | null;
        trinket_2: string | null;
        weapon: string | null;
        weapon_matk: number | null;
        weapon_patk: number | null;
      } | null)[]
    | null;
  /**
   * @maxItems 8
   */
  combat_party?: (string | null)[] | null;
  cutscene_count?: number | null;
  /**
   * @maxItems 16
   */
  defense_rating?: (number | null)[] | null;
  dialog_boxes?: number | null;
  encounter_xp?: number | null;
  /**
   * @maxItems 16
   */
  enemies?:
    | ({
        hp: number | null;
        label: string | null;
        level: number | null;
        matk: number | null;
        max_hp: number | null;
        mdef: number | null;
        patk: number | null;
        pdef: number | null;
      } | null)[]
    | null;
  garl_hp_percent?: number | null;
  /**
   * @maxItems 40
   */
  garl_levelups?:
    | ({
        hp: number | null;
        matk: number | null;
        mdef: number | null;
        patk: number | null;
        pdef: number | null;
        sp: number | null;
      } | null)[]
    | null;
  garl_max_hp?: number | null;
  garl_max_sp?: number | null;
  /**
   * @maxItems 8
   */
  garl_trinket0_mods?:
    | ({
        amount: number | null;
        kind: string | null;
        stat: number | null;
      } | null)[]
    | null;
  /**
   * @maxItems 8
   */
  garl_trinket1_mods?:
    | ({
        amount: number | null;
        kind: string | null;
        stat: number | null;
      } | null)[]
    | null;
  /**
   * @maxItems 16
   */
  garl_upgrades?:
    | ({
        count: number | null;
        stat: number | null;
      } | null)[]
    | null;
  in_combat?: number | null;
  /**
   * @maxItems 256
   */
  inventory?:
    | ({
        guid: string | null;
        qty: number | null;
      } | null)[]
    | null;
  /**
   * @maxItems 512
   */
  item_catalog?:
    | ({
        guid: string | null;
        kind: string | null;
        label: string | null;
      } | null)[]
    | null;
  leader?: string | null;
  level_guid?: string | null;
  /**
   * @maxItems 256
   */
  levels?:
    | ({
        guid: string | null;
        label: string | null;
        level_id: string | null;
      } | null)[]
    | null;
  main_character?: string | null;
  /**
   * @maxItems 8
   */
  party?: (string | null)[] | null;
  party_progress?: {
    level: number | null;
    total_xp: number | null;
    unspent_xp: number | null;
  } | null;
  party_resources?: {
    combo_points: number | null;
    max_combo_points: number | null;
    ult_points: number | null;
  } | null;
  paused?: number | null;
  roster_downed?: number | null;
  roster_hp_total?: number | null;
  upgrade_step?: {
    hp: number | null;
    matk: number | null;
    mdef: number | null;
    patk: number | null;
    pdef: number | null;
    sp: number | null;
  } | null;
  valere_hp_percent?: number | null;
  /**
   * @maxItems 40
   */
  valere_levelups?:
    | ({
        hp: number | null;
        matk: number | null;
        mdef: number | null;
        patk: number | null;
        pdef: number | null;
        sp: number | null;
      } | null)[]
    | null;
  valere_max_hp?: number | null;
  valere_max_sp?: number | null;
  /**
   * @maxItems 8
   */
  valere_trinket0_mods?:
    | ({
        amount: number | null;
        kind: string | null;
        stat: number | null;
      } | null)[]
    | null;
  /**
   * @maxItems 8
   */
  valere_trinket1_mods?:
    | ({
        amount: number | null;
        kind: string | null;
        stat: number | null;
      } | null)[]
    | null;
  /**
   * @maxItems 16
   */
  valere_upgrades?:
    | ({
        count: number | null;
        stat: number | null;
      } | null)[]
    | null;
  zale_hp_percent?: number | null;
  /**
   * @maxItems 40
   */
  zale_levelups?:
    | ({
        hp: number | null;
        matk: number | null;
        mdef: number | null;
        patk: number | null;
        pdef: number | null;
        sp: number | null;
      } | null)[]
    | null;
  zale_max_hp?: number | null;
  zale_max_sp?: number | null;
  /**
   * @maxItems 8
   */
  zale_trinket0_mods?:
    | ({
        amount: number | null;
        kind: string | null;
        stat: number | null;
      } | null)[]
    | null;
  /**
   * @maxItems 8
   */
  zale_trinket1_mods?:
    | ({
        amount: number | null;
        kind: string | null;
        stat: number | null;
      } | null)[]
    | null;
  /**
   * @maxItems 16
   */
  zale_upgrades?:
    | ({
        count: number | null;
        stat: number | null;
      } | null)[]
    | null;
}
