/* Generated by scripts/gen-types.mjs from the vendored contract schema. Do not edit by hand;
 * re-run `npm run gen-types` after `npm run sync-contracts`. */

// The version views of this contract are written against; see scripts/gen-types.mjs.
export type * from './2.0';
