/**
 * Generate TypeScript types from the vendored contract schemas.
 *
 *   npm run gen-types            # write src/contracts/<id>/<version>.ts
 *   npm run gen-types -- --check # fail if any generated file is stale
 *
 * One file per contract version, each exporting `Values`: the `values` object that version
 * describes. These replace hand-written types, which were a second description of the same shape
 * that nothing kept in step with the first. A view imports its contract through an alias
 * (`@contracts/sea-of-stars`, see tsconfig.json), which is what lets the type-check run the same
 * view against every version in its range.
 *
 * Nothing about nullability is decided here: the schema says every value may be `null`, and the
 * types say so too. Top-level properties are optional as well, because a diff names only what
 * changed and a snapshot may predate a watch.
 */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';
import { contractVersions, loadViews } from './views.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');

const BANNER = `/* Generated by scripts/gen-types.mjs from the vendored contract schema. Do not edit by hand;
 * re-run \`npm run gen-types\` after \`npm run sync-contracts\`. */`;

let stale = 0;

function emit(out, text) {
  if (check) {
    if (!existsSync(out) || readFileSync(out, 'utf8') !== text) {
      console.error(`${relative(root, out)} is stale: run npm run gen-types`);
      stale++;
    }
    return;
  }
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, text);
  console.log(`wrote ${relative(root, out)}`);
}

const views = loadViews(root);
const ids = [...new Set(views.map((view) => view.contract.id))].sort();
for (const id of ids) {
  const versions = contractVersions(root, id);
  for (const { text, schemaFile } of versions) {
    const schema = JSON.parse(readFileSync(schemaFile, 'utf8'));
    // The title is what json-schema-to-typescript names the root type after; every version's root
    // is called `Values`, so a view's imports do not change from one version to the next.
    const ts = await compile({ ...schema, title: 'Values' }, 'Values', {
      bannerComment: BANNER,
      // Objects the schema leaves open still get no index signature: reading a property the
      // contract does not declare should not compile, even though the data may carry one.
      additionalProperties: false,
      // The schema caps collections with maxItems; left on, that would become a union of every
      // tuple length up to the cap, which is precise and useless.
      maxItems: -1,
      strictIndexSignatures: true,
      format: true,
      style: { singleQuote: true, printWidth: 110 },
    });
    emit(join(root, 'src', 'contracts', id, `${text}.ts`), ts);
  }

  // `@contracts/<id>` resolves here by default: the oldest version any view of this contract
  // accepts, because that is the version such a view is written against. The type-check matrix
  // points the alias at each later version in turn.
  const floor = views
    .filter((view) => view.contract.id === id)
    .map((view) => view.contract.range.min)
    .sort((a, b) => a.major - b.major || a.minor - b.minor)[0];
  const pinned = versions.find((v) => v.version.major === floor.major && v.version.minor >= floor.minor);
  if (!pinned) {
    console.error(`no vendored ${id} version at or above ${floor.major}.${floor.minor}; run npm run sync-contracts`);
    process.exit(1);
  }
  emit(
    join(root, 'src', 'contracts', id, 'index.ts'),
    `${BANNER}\n\n// The version views of this contract are written against; see scripts/gen-types.mjs.\nexport type * from './${pinned.text}';\n`,
  );
}
process.exit(stale ? 1 : 0);
